services:
  - type: web
    name: kriyeta-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.12"
      - key: GROQ_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
